---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Day 2: Password Philosophy

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)

library(tidyverse)
library(scales)
```

```{r}
input <- read_file("../input/02 - Password Philosophy - Input.txt") %>%
  str_split("\\n") %>%
  unlist() %>%
  tibble(input = .)

cleaned_input <- input %>%
  filter(nchar(input) > 0) %>%
  extract(input, c("min", "max", "letter", "password"), 
          regex = "(\\d+)-(\\d+) (\\w): (\\w*)", remove = FALSE) %>%
  mutate_at(c("min", "max"), as.numeric)
```

### Puzzle 1

```{r}
solution1 <- cleaned_input %>%
  mutate(n_occurences = map_dbl(str_match_all(password, letter), length), 
         is_valid = n_occurences >= min & n_occurences <= max) %>% 
  filter(is_valid)
```

There are `r nrow(solution1)` valid passwords. 

### Puzzle 2

```{r}

char_at <- function(x, i) substr(x, i, i)

solution2 <- cleaned_input %>%
  mutate(min_char = map2_chr(password, min, char_at),
         max_char = map2_chr(password, max, char_at)) %>%
  mutate(is_valid = xor(letter == min_char, letter == max_char)) %>%
  filter(is_valid)
```

There are `r nrow(solution2)` valid passwords. 