---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Day 3: Toboggan Trajectory

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)

library(tidyverse)
library(scales)
```

```{r}
input <- read_file("../input/03 Tobaggan Trajectory - Input.txt") %>%
  str_split("\\n") %>%
  unlist() %>%
  tibble(input = .)

cleaned_input <- input %>%
  mutate(row = row_number(),
         path = map(input, ~ str_split(., pattern = "")[[1]])) %>%
  unnest(path) %>%
  mutate(is_tree = ifelse(path == "#", TRUE, FALSE)) %>%
  group_by(row) %>%
  mutate(column = row_number()) %>%
  ungroup() %>%
  select(row, column, is_tree)
```

### Puzzle 1

```{r puzzle1, fig.align="center"}
# y - y1 = m(x - x1) -> x1 + (y - y1) / m
# x1 = 1, y1 = 1
get_x <- function(y, down, right) {
  m = down / right
  
  x <- 1 + ((y - 1) / m)
}

solution1 <- cleaned_input %>%
  mutate(x = get_x(row, 1, 3), 
         x_mod = ifelse(x %% 31 == 0, 31, x %% 31),
         position_check = as.double(column) == x_mod) %>%
  filter(position_check)

n_trees_hit <- solution1 %>% filter(is_tree) %>% nrow()

solution1 %>%
  ggplot(aes(column, -row, color = is_tree)) + 
  geom_point() + 
  labs(title = paste("Tobaggan Path -", n_trees_hit, "trees hit."),
       x = "Column",
       y = "Row", 
       color = "Tree?") + 
  theme_minimal()
```

### Puzzle 2

```{r puzzle2, fig.height=8, fig.width=12, fig.align="center"}
slopes <- tibble(
  right = c(1, 3, 5, 7, 1), 
  down  = c(1, 1, 1, 1, 2)
)

solution2 <- cleaned_input %>%
  full_join(slopes, by = character()) %>%
  mutate(x = pmap_dbl(list(row, down, right), get_x), 
         x_mod = ifelse(x %% 31 == 0, 31, x %% 31),
         position_check = as.double(column) == x_mod) %>%
  filter(position_check, x %% 1 == 0)

solution2_value <- solution2 %>%
  group_by(right, down) %>%
  summarise(num_trees = sum(is_tree), .groups = "drop") %>%
  pull(num_trees) %>%
  prod() %>%
  formattable::comma(digits = 0)

solution2 %>%
  group_by(right, down) %>%
  mutate(num_trees = sum(is_tree)) %>%
  ungroup() %>%
  mutate(group_name = glue::glue("Slope = { down }/{ right }; #trees = { num_trees }")) %>%
  ggplot(aes(column, -row, color = is_tree)) + 
  geom_point() + 
  facet_wrap(~ group_name) + 
  labs(title = "Tobaggan Paths for each slope", 
       subtitle = paste("Puzzle solution:", solution2_value),
       x = "Column",
       y = "Row", 
       color = "Tree?") + 
  theme_minimal()
```
